services:
  - type: web
    name: zeechei-discord-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: YT_COOKIES
        sync: false
